const { app,ws_app } = require('./app.js')
const { http_router,ws_router,static_file_router } = require('./router/index.js')
require('./routes/index.js')
http_router.init({ app })
ws_router.init({ app: ws_app,basePath: '/ws' })
// static_file_router.init({ app,basePath: '/static' })